services:
  - type: web
    name: cryptogamer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13